spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://192.168.1.242:3306/cdot_business?useUnicode=true&useSSL=false&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver