# Spring properties
server:
  port: 8930
spring:
  #  profiles: local
  application:
    name: es6.8-demo

elasticsearch:
  ip: 127.0.0.1
  port: 9300
  cluster-name: elasticsearch
  node-name: node1

